### ISSUE TITLE
Bad link in subscription digest email 

### ISSUE THREAD

**Issue by bdeboe** [intersystems-community/developer-community#806] opened 2022-11-23 07:59 UTC
When clicking on a tag next to an article's title (by accident :-) ) in a subscription digest email, I ended up at https://community.intersystems.com/taxonomy_terms/1341, which yielded a page not found error. When clicking on the tag in the article itself (so on the DC web page rather than in the email), I end up at the right link: https://community.intersystems.com/tags/intersystems-official

**Comment by lelikone** [comment] 2022-11-23 10:52
@bdeboe 
Hello Benjamin!
Thank you for finding the error, we will try to fix it as soon as possible

**Comment by lelikone** [comment] 2022-11-24 09:17
@bdeboe
Hello Benjamin!
Please forward me this letter. As I cannot detect the error.

**Comment by bdeboe** [comment] 2022-11-24 10:08
done 👍

**Comment by lelikone** [comment] 2022-11-24 10:19
Thank you! I found the mistake, I'll fix it soon.

**Comment by lelikone** [comment] 2022-11-25 13:34
@bdeboe
Hello Benjamin!
I made a change. New emails should come with the correct link.
If all goes well from now on, please close the problem as solved.

**Comment by Lena-Ev** [comment] 2022-11-29 08:50
Hi Benjamin!
As the issue is solved we close it, please reopen if you still have this issue.

**Closed as completed by Lena-Ev** 2022-11-29 08:50 UTC
